# Generated by Django 2.2.1 on 2019-05-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20190516_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Rated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Year',
            field=models.IntegerField(default=0),
        ),
    ]
