# Generated by Django 2.2.1 on 2019-05-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20190523_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Released',
        ),
    ]
