# Generated by Django 2.2.1 on 2019-05-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_remove_movies_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Released',
            field=models.DateField(default=None),
        ),
    ]
