# Generated by Django 2.2.1 on 2019-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20190523_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Runtime',
            field=models.CharField(default='', max_length=255),
        ),
    ]
