# Generated by Django 2.2.1 on 2019-05-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20190523_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='DVD',
            field=models.CharField(default='', max_length=255),
        ),
    ]
