# Generated by Django 2.2.1 on 2019-05-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_auto_20190523_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AddField(
            model_name='movies',
            name='ID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
