# Generated by Django 2.2.1 on 2019-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_auto_20190523_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='totalSeasons',
            field=models.CharField(default='', max_length=255),
        ),
    ]
