# Generated by Django 2.2.1 on 2019-05-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_movies_totalseasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Year',
            field=models.CharField(default='', max_length=255),
        ),
    ]
