# Generated by Django 2.2.1 on 2019-05-23 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_auto_20190523_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
