# Generated by Django 2.2.1 on 2019-05-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_comments_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top',
        ),
    ]
